name: nebra-helium-miner
base: core20
adopt-info: miner
summary: Miner for helium blockchain
description: |
  Miner for the helium blockchain. Thsi snap requires the i2c and log-observe interfaces
  to be connected to work properly, run:

      snap connect helium-miner:i2c pi:i2c-1
      snap connect helium-miner:log-observe

  after installing the snap.
  All data, log files etc are stored under /var/snap/helium-miner/common

grade: stable
confinement: strict

architectures:
  - build-on: arm64
    run-on: arm64

apps:
  miner:
    command: miner/bin/miner foreground
    daemon: simple
    environment:
      COOKIE: "miner"
      HOME: "$SNAP_COMMON"
      PATH: "/usr/lib/erlang/bin:$SNAP/miner/bin:$PATH"
      RELX_OUT_FILE_PATH: "/tmp"
    plugs:
      - i2c
      - log-observe
      - network
      - network-bind

layout:
  /usr/lib/erlang:
    bind: $SNAP/usr/lib/erlang
  /var/log/miner:
    bind: $SNAP_COMMON/log

parts:
  erlang:
    plugin: dump
    source: https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_22.3.4.2-1~ubuntu~focal_arm64.deb
    stage-packages:
      - libtinfo6
  miner:
    after: [ erlang ]
    plugin: make
    source: https://github.com/helium/miner.git
    build-packages:
      - autoconf
      - automake
      - bison
      - cargo
      - cmake
      - doxygen
      - flex
      - g++
      - libclang-dev
      - libdbus-1-dev
      - libgmp-dev
      - libsnappy-dev
      - libsodium-dev
      - libssl-dev
      - libtool
    stage-packages:
      - libsodium23
    build-environment:
      - PATH: "${SNAPCRAFT_STAGE}/usr/lib/erlang/bin:$PATH"
      - CFLAGS: "-U__sun__"
      - ERLANG_ROCKSDB_OPTS: "-DWITH_BUNDLE_SNAPPY=ON -DWITH_BUNDLE_LZ4=ON"
      - ERL_COMPILER_OPTIONS: "[deterministic]"
    override-build: |
      # use erlang from staging dir
      ln -sf $SNAPCRAFT_STAGE/usr/lib/erlang /usr/lib/erlang
      # set package version from miner upstream version
      VER="$(grep -m1 "{release, {miner," $SNAPCRAFT_PART_SRC/rebar.config | sed 's/^.* "//;s/".*$//')"
      echo "setting snap version to $VER"
      snapcraftctl set-version "$VER"
      # build and install
      make release && \
      cp -av $SNAPCRAFT_PART_BUILD/_build/prod/rel/miner $SNAPCRAFT_PART_INSTALL/
  blockchain-api:
    after: [ miner ]
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/miner/updates
      wget https://github.com/helium/blockchain-api/raw/master/priv/prod/genesis \
        --output-document=$SNAPCRAFT_PART_INSTALL/miner/updates/genesis
    build-packages:
      - wget
